jenkins-x/jx3-versions

apps/stable/nginx-ingress/values.yaml.gotmpl
The extraArgs approach is more "hard-coded"
=> fix: use publishService.enabled instead of extraArgs

charts/jenkins-x/bucketrepo/secret-schema.yaml
This PR populates the bucket URL in bucketrepo's secret-schema.yaml if the corresponding key was set in jx-requirements.yaml, keeping the previous behaviour of using local storage if it was not set
=> fix(charts/bucketrepo): use storage repository URL from jx-requirements if available

charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
default tekton to use the same gitUrl for the main jenkins-x repo https://github.com/jenkins-x-charts/jxboot-helmfile-resources/blob/618c8e89e741c8a5e2f54dd8755fa3bceca1e7a8/jxboot-helmfile-resources/templates/tekton-git-secret.yaml#L10
=> fix: tekton use gitUrl from jxRequirements

charts/jx3/health-checks-install/defaults.yaml, charts/jx3/health-checks-jx/defaults.yaml, charts/jx3/jx-kh-check/defaults.yaml, charts/jx3/jx-pipelines-visualizer/defaults.yaml
See https://kubernetes.slack.com/archives/C9MBGQJRH/p1602842034264800\?thread_ts\=1602763034.179300\&cid\=C9MBGQJRH for context
=> fix: lock down jx-pipelines-visualizer & jx-kh-check versions

charts/jenkins-x/lighthouse/values.yaml.gotmpl
to allow less boilerplate when using in-repo tekton pipelines
=> fix: upgrade lighthouse

git-operator/job-gsm.yaml, git-operator/job-vault.yaml, git-operator/job.yaml
so that we can handle http better and reuse the git init commands configured on the operator to deal with insecure registries
=> fix: lets clone via: jx gitops git clone

charts/jx3/jx-build-controller/values.yaml.gotmpl
Although S3 buckets are global, go-cloud and most AWS SDKs need AWS_REGION to work. Reference: https://github.com/google/go-cloud/issues/1357
=> fix: Add env-var for AWS_REGION

charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
`jx-pipelines-visualizer` would need this to fetch logs from S3.
=> chore: Add annotation for workload identity in AWS

charts/jx3/jx-pipelines-visualizer/defaults.yaml, charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
To read from log storage in AWS S3. Depends on: https://github.com/jenkins-x/jx-pipelines-visualizer/pull/41
=> fix(pipelines-visualizer): Add env-var for AWS_REGION

.gitignore, charts/jx3/jx-build-controller/values.yaml.gotmpl
Pass GIT_SECRET_SERVER as is so that the git credential store can be created with the correct scheme.
Depends on https://github.com/jenkins-x/jx-helpers/pull/132
=> Git secret server pass as url

charts/jenkins-x/jx-build-templates/defaults.yaml, charts/jenkins-x/jx/defaults.yaml, charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml, charts/jenkins-x/lighthouse/defaults.yaml, charts/jenkins-x/nexus/defaults.yaml, charts/jenkins-x/sso-operator/defaults.yaml, charts/jx3/jx-cli/defaults.yaml, charts/jx3/jx-kh-check/defaults.yaml, charts/jx3/jx-pipelines-visualizer/defaults.yaml, charts/jx3/slack/defaults.yaml
* updated chart [jenkins-x/jx](https://github.com/jenkins-x/jx) from `2.0.1143` to `2.1.155`
* updated chart [jenkins-x/jx-build-templates](https://github.com/jenkins-x-charts/jx-build-templates) from `0.0.1475` to `0.0.1505`
* updated chart [jenkins-x/jxboot-helmfile-resources](https://github.com/jenkins-x-charts/jxboot-helmfile-resources) from `1.0.25` to `1.0.26`
* updated chart [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse) from `0.0.903` to `0.0.906`
* updated chart [jenkins-x/nexus](https://github.com/jenkins-x-charts/nexus) from `0.1.35` to `0.1.37`
* updated chart [jenkins-x/sso-operator](https://github.com/jenkins-x/sso-operator) from `1.2.49` to `1.2.50`
* updated chart [jx3/jx-cli](https://github.com/jenkins-x/jx-cli) from `3.0.402` to `3.1.116`
* updated chart …
=> chore: upgrade charts

src/Makefile.mk
To support mutliple releases of the same chart the release name is required in the hemlfile template path, otherwise the latter clobber the first
Full explanation https://github.com/jenkins-x/jx3-versions/pull/2003
Requires https://github.com/jenkins-x/jx-gitops/pull/527
=> fix: include the release name in helmfile template

charts/stable/chartmuseum/defaults.yaml
The minimum version that supports serviceaccount annotations is 2.6.1 (https://github.com/helm/charts/pull/19724/files). We used IRSA to use AWS S3 as storage for chartmuseum. We tested the latest available chart version. The 'stable' repo itself is deprecated, but let's use the latest available version there before switching to another repo.
=> chore: Bump up chartmuseum version

charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
this will allow the UI to access the long-term storage directly, to view an old pipeline that has been garbage collected in the cluster
related to https://github.com/jenkins-x-plugins/jx-build-controller/pull/11
=> fix: configure the pipelines-visualizer to access the logs storage

charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
reverting a recent change from https://github.com/jenkins-x/jx3-versions/commit/ac3ffb2579791ba8cffa3522267b0b6dde729c80#diff-f428f8a805c29d78b1e8603fa794a1b809f44ab9c54b0b57dc433c183afa920aL84
we'll need to look at enabling the external secret change above again once we re-enable a maven BDD test
=> fix: nexus password missing from maven settings xml when using gsm

charts/jenkins-x/lighthouse/values.yaml.gotmpl
note that I've added a workaround while waiting for https://github.com/jenkins-x/lighthouse/pull/1259 to be merged
(because the lighthouse pipelines are broken for the moment...)
=> chore: enable prometheus scraping for lighthouse

charts/jx3/jx-pipelines-visualizer/defaults.yaml, charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
so that we don't get 404 when following links to the dashboard
see https://github.com/jenkins-x-plugins/jx-build-controller/issues/13
and https://github.com/jenkins-x-plugins/jx-build-controller/pull/27
and https://github.com/jenkins-x/jx-pipelines-visualizer/pull/104
=> feat: allow pipelines-visualizer to get pipelineruns from longterm storage

charts/kuberhealthy/kuberhealthy/defaults.yaml, charts/kuberhealthy/kuberhealthy/values.yaml.gotmpl
- upgrade kuberhealthy to the latest version: chart "54" (yes...) and app version 2.4.0 (instead of 2.2.0)
- enable prometheus scraping of kuberhealthy metrics
=> chore: upgrade kuberhealthy & enable prometheus scraping

charts/grafana/grafana/values.yaml.gotmpl, charts/jx3/grafana-dashboard/defaults.yaml, charts/prometheus-community/prometheus/values.yaml
- update grafana-dashboard chart & define a default dashboard (instead of using grafana's own default)
- automatically detect grafana datasources & notifiers stored in ConfigMaps in any namespaces - with the right labels
- `jenkins-x.io/grafana-datasource`
- `jenkins-x.io/grafana-notifier`
- setup a default grafana alert notifier to fwd the alert to prometheus alertmanager
- configure a few prometheus alerts for cert-manager
- certificate not ready
- certificate will expire in 21 days or less
=> chore: configure grafana & prometheus for alerting

charts/repositories.yml
so that people can write helmfiles referencing the prometheus chart without explicitly referencing the prometheus repository
=> fix: add missing mapping for prometheus helm repository

charts/jx3/lighthouse/values.yaml.gotmpl
now that https://github.com/jenkins-x/lighthouse/pull/1259 has been merged, we don't need this workaround anymore
=> chore: cleanup lighthouse values

charts/jx3/cd-indicators/defaults.yaml, charts/jx3/cd-indicators/secret-schema.yaml, charts/jx3/cd-indicators/values.yaml
add default values and secret schema for https://github.com/jenkins-x/cd-indicators
a few notes:
- the chart has an internal dependency on the postgresql chart (enabled by default)
- the postgresql password is auto-generated (using the secret schema)
- it re-use the existing grafana instance, by providing grafana dashboards and datasources configmap/secrets with the right label
- the chart should be added to the `helmfiles/jx/helmfile.yaml` file in the `jx` namespace (because it needs the `lighthouse-hmac-token` secret)
=> chore: add cd-indicators chart

schedulers/default.yaml, schedulers/environment.yaml, schedulers/in-repo.yaml, schedulers/jx-meta-pipeline.yaml
this change registers the https://github.com/jenkins-x/cd-indicators app as an external lighthouse plugin on all default schedulers, so that by default events for all repos using these schedulers will be forwarded by lighthouse (webhooks) to the cd-indicators app, so that we can get pullrequest and deployment events, and graph them in grafana.
note that for the moment, cd-indicators is not deployed by default, which means that lighthouse won't be able to make its http request, and instead of logging at the `info` level (that it forwarded the event to our plugin), it will log at the `error` that the call failed - see https://github.com/jenkins-x/lighthouse/blob/fa1e4e162244df54966d7585260a4be0e2c7fc45/pkg/util/externalplugins.go#L183-L187
ideally we'll install cd-indicators by default, and …
=> chore: register cd-indicators as an ext lighthouse plugin

charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
to enable the "trace" button in the UI, to open grafana to visualize the pipeline trace
note that:
- even if this is enabled, the button won't be visible if the pipeline has no trace (= no annotation on the PipelineActivity with the trace ID)
- to build the grafana ingress, I had to fix the namespaceSubDomain - see the comment in the code. it would be good to find a better way to do it...
=> chore: link jx-pipelines-visualizer with grafana

charts/jx3/jx-build-controller/values.yaml.gotmpl
see https://github.com/jenkins-x-plugins/jx-build-controller/pull/28
this enable the "tracing" feature of the build-controller, using our internal grafana/tempo instance.
note that even if the observability stack is not installed, it won't fail: if the endpoint doesn't exist, the feature will just be disabled with a warning msg explaining how to enable it
=> feat: enable tracing in build-controller

charts/grafana/grafana/values.yaml.gotmpl
see https://kubernetes.slack.com/archives/C9MBGQJRH/p1619019594489800?thread_ts=1619019176.489400&cid=C9MBGQJRH
the grafana chart uses a random function for the adminPassword by default, and each time we render the templates we end up with a new password, so a new secret checksum, and a change in the deployment.
this fix sets a static password to avoid this issue.
note that this fake password is never used, because it is replaced by the password from the external secret.
=> fix: ensure grafana secret checksum won't change every time

charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
To use minio as log storage, query parameters are required for the log url e.g.
```
storage:
- name: logs
url: s3://jx3?endpoint=minio.minio.svc.cluster.local:9000&disableSSL=true&s3ForcePathStyle=true&region=ignored
- name: reports
url: s3://jx3?endpoint=minio.minio.svc.cluster.local:9000&disableSSL=true&s3ForcePathStyle=true&region=ignored
```
The PR uses helms urlParse and urlJoin to place the golang template in the path portion of the url, rather than appending, which ends up placing it as part of the querystring
=> feat: support jx-requirements log url with a querystring

charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl, secrets/secretsManager/mapping/secret-mappings.yaml, secrets/systemManager/mapping/secret-mappings.yaml
This commit adds AWS secrets configuration
to the external-secrets chart. Following the chart
documentation
https://github.com/external-secrets/kubernetes-external-secrets/tree/6.3.0/charts/kubernetes-external-secrets#installing-the-chart
A single Jenkins X Service Account role will need to be setup
Also updated mappings for systemManager and secretsManager
=> feat: added aws secrets configuration

charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
A separate role is created for SSM and SecretsManager (with Terraform setup),
so I have updated the values accordingly
=> fix: updated role names for aws secrets

charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
The default polling of 1000ms is too short and triggers the rate limiting.
=> fix: increase polling interval if we're using Azure Key Vault

schedulers/default.yaml, schedulers/environment.yaml, schedulers/in-repo.yaml, schedulers/jx-meta-pipeline.yaml
update the default schedulers to register the lighthouse webui as an external plugin, so that it can receive webhook events from lighthouse-webhooks
=> chore: configure the lighthouse web ui

charts/jx3/lighthouse-webui-plugin/values.yaml.gotmpl
so that events are not lost when the pod restarts
=> chore(lighthouse-webui-plugin): enable persistence by default

schedulers/default.yaml, schedulers/environment.yaml, schedulers/in-repo.yaml, schedulers/jx-meta-pipeline.yaml
related to https://github.com/jenkins-x/lighthouse/pull/1324
instead of using the pipelines visualizer, let's use the new lighthouse webui and its "merge status" page
it might help people understand why keeper is not merging a PR
=> chore: use the new LH webui when reporting status updates

charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl, secrets/systemManager/mapping/secret-mappings.yaml
renamed parameter-store to system-manager to maintain standard.
Also updated the mapping file as that still said vault
=> fix: use external secrets name as standard

charts/jx3/lighthouse-webui-plugin/values.yaml.gotmpl
bitbucketcloud does not support hmac. this will set the secret as
optional.
=> fix: make hmac optional for bitbucketcloud

charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
so we align the jx-boot image with the current jx version in the CronJobs for GC'ing resources
=> fix: use correct jx image

charts/jxgh/jxboot-helmfile-resources/secret-schema.yaml
fixes https://github.com/jenkins-x/jx3-versions/issues/2768
=> fix: use central as default mirror

charts/external-secrets/kubernetes-external-secrets/defaults.yaml
Fixes a bunch of CVEs: https://github.com/external-secrets/kubernetes-external-secrets/releases/tag/8.2.1, probably best to upgrade to the latest version (8.3.0)
=> refactor: upgrade external secrets to 8.3.0

charts/jxgh/jx-build-controller/defaults.yaml, charts/jxgh/jx-preview/defaults.yaml, charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Tekton upgrade requires a PR from pipeline catalog, which will be merged this weekend, but we can bump other charts in the meantime.
=> chore: manually bump charts other than tkn

charts/jetstack/cert-manager/defaults.yaml
Upgrade notes https://cert-manager.io/docs/installation/upgrading/upgrading-1.1-1.2/
=> fix: Upgrade cert-manager to 1.2.0

src/Makefile.mk
Related Issue: https://github.com/jenkins-x-plugins/jx-secret/issues/359
With these changes we are able to precise another vault mount point.
We also needed to add the `JX_VAULT_ROLE` & `JX_VAULT_MOUNT_POINT` in order to have the right information during the secret populate
=> chore: make external vault works with these changes

.github/workflows/update-charts/updatebot.yaml
Since we are already on 1.7.X version of cert manager, we can update start auto updating cert manager charts. Same for external secrets chart.
=> fix: update certmanager and external secrets periodically

charts/bitnami/external-dns/defaults.yaml
6.0.2 can no longer be do downloaded
Trying latest version
=> chore: Upgrade external-dns

.lighthouse/jenkins-x/bdd/remote/ci.sh, .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-kubevault.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl, .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
This is to prevent errors in the builds like
```
+ jx ctx -b
ERROR: failed to load plugin jx-context: can't find latest version of plugin: {"message":"API rate limit exceeded for 35.225.186.19. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"[https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting)
```
`jx ns -b` and `jx ctx -b` gives the same output.
=> fix: Don't download context

.github/workflows/update-charts/updatebot.yaml
Tekton upgrades need more testing, and hence we should disable the auto upgrades for now (re-enable it after we expand our tests to include testing on existing clusters)
=> chore: disable tekton chart auto upgrade

src/Makefile.mk
On our case:
- Since k8s in 1.21, with the BoundServiceAccountTokenVolume feature enabled in beta, kubernetes-external-secrets pod is using a jwt token with an issuer that is same than the one we configured on our cluster.
- jx-secret populate command is using a jwt token with an issuer kubernetes.io/service-account-token, because it just takes the service account secret token, instead of a Token generated by the TokenRequestAPI: it's here on this function it's happening; https://github.com/jenkins-x-plugins/secretfacade/blob/master/pkg/iam/vaultiam/iam.go#L56
Because on our case we can't yet disable the vault issuer validation, we have decided to create 2 different vault auth mount point  with different issuer so it's all fine for both jx secret convert & jx secret populate commands, …
=> chore: specify vault role & mount point for populate and es

src/Makefile.mk
When deploying a separate staging/production environment without kuberhealthy, there are no CRDs and the boot job fails. See https://kubernetes.slack.com/archives/C9MBGQJRH/p1659537849699819
=> fix: only apply CRDs if they exist

src/Makefile.mk
the contents of https://github.com/jenkins-x/jx3-versions/blob/62fc4d6bff12a1c4bacfc87f6291d102fda5ef35/src/Makefile.mk#L62-L69 leads users to believe that they are able to configure additional helmfile template flags via the `HELMFILE_TEMPLATE_FLAGS` env var. this feature seems to have been lost in translation in [this PR](https://github.com/jenkins-x/jx3-versions/pull/1823). [according to slack records](https://kubernetes.slack.com/archives/C9MBGQJRH/p1616755962449000?thread_ts=1616755638.448000&cid=C9MBGQJRH), there doesn't seem to be any explicit reason this was disabled
i personally have a use case of adding the flag `--skip-tests` to disable some noisy helm chart test pods rendered by `helmfile template`. ref https://github.com/jenkins-x-plugins/jx-gitops/pull/885
=> fix: use HELMFILE_TEMPLATE_FLAGS in 'helmfile template'

charts/jxgh/jx-preview/defaults.yaml, charts/jxgh/jx-slack/defaults.yaml, charts/jxgh/jx-ui/defaults.yaml, charts/jxgh/vault-instance/defaults.yaml
Charts bumped:
- jx-preview
- jx-slack
- jx-ui
- vault-instance
The auto upgrades are blocked because tests fail, trying to isolate the issue
=> chore: manual bump of charts

charts/external-secrets/external-secrets/defaults.yaml, charts/external-secrets/external-secrets/values.yaml.gotmpl
=> feat: add external secrets charts

git-operator/job-azurekeyvault.yaml, git-operator/job-gsm.yaml, git-operator/job-vault.yaml, git-operator/job.yaml, src/Makefile.mk
This means that jx-gcjobs isn't needed anymore
This is particularly useful in remote clusters where you otherwise don't need jxboot-helmfile-resources there
While at it I also fix a typo in comment
=> feat: Add ttlSecondsAfterFinished to jobs

charts/jetstack/cert-manager/values.yaml.gotmpl
When upgrading the cluster (jx gitups cluster) and cert-manger is upgraded the boot job fails due to the startupapicheck:
job.batch/cert-manager-startupapicheck apply failed: error when applying patch:...: field is immutable
Disabling job to prevent problem
=> fix: cert-manager upgrade problem

charts/repositories.yml
I don't think it hurts to have it here per se, but it can't be used so can as well be removed.
The repo gives
Error: looks like "https://kubernetes-charts.banzaicloud.com" is not a valid chart repository or cannot be reached: Get "https://kubernetes-charts.banzaicloud.com/index.yaml": x509: certificate has expired or is not yet valid: current time 2022-12-19T08:18:17Z is after 2022-12-19T07:42:55Z
=> fix: remove failing and unused repository

src/kpt-live-apply-wrapper.sh, src/ns-reconciled
Also adding hooks for scripts to run when reconciliation has succeeded
This makes sense when jenkins-x/jx#8466 is fixed
=> feat: release notes

charts/bitnami/external-dns/defaults.yaml
the chart for the previous version are unavailable
=> fix: upgrade external-dns to 6.7.0

charts/bitnami/external-dns/defaults.yaml
This upgrade contains this fix which affects users https://github.com/kubernetes-sigs/external-dns/pull/2913
=> chore: external-dns to 6.12.2

.github/workflows/update-go.yml, .lighthouse/jenkins-x/bdd/terraform-ci.sh, .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Mainly to prevent annoying error mail
But maybe it is useful to run....
=> fix: update-go action

src/get-selectors-and-clean.sh
This PR resolves the problems with source repositories being removed if a values file is modified seen in [this issue](https://github.com/jenkins-x/jx3-versions/issues/3491).
The change means that if anything is modified in the jx namespace then no helmfile selectors are added so all namespaces get properly templated.
=> fix: if anything is changed in jx ns then run without selector

charts/bitnami/external-dns/defaults.yaml
This upgrade includes a fix for nil pointer errors due to ingresses longer than 63 characters
https://github.com/kubernetes-sigs/external-dns/pull/3294
=> chore: external-dns to 6.13.1

.lighthouse/jenkins-x/bdd/terraform-ci.sh, src/Makefile.mk
The most common cause of merge conflicts preventing PR in cluster repository is from releases.yaml. Only updating this file in the jx-boot job should prevent this problem.
Also I don't think jx-boot should ever do force push, but if it does it certainly shouldn't overwrite unknown commits
Fixes jenkins-x/jx#8247
=> fix: prevent conflicts by not updating docs in PR

src/Makefile.mk
This fixes a regression in #3573. The intention was that even if `jx gitops helmfile report` would always change the files in doc there wouldn't an infinite loop. But the logic was faulty and here is new, better tested, attempt.
=> fix: fix faulty negation of expression

.lighthouse/jenkins-x/bdd/terraform-ci.sh
Trying to avoid timeout when the test really did succeed:
https://dashboard-jx.infra.jenkins-x.rocks/ns-jx/jenkins-x/jx3-versions/PR-3719/2
=> fix: increase BDD test timeout

charts/bitnami/external-dns/secret-schema.yaml, charts/bitnami/external-dns/values.yaml.gotmpl
Adds the cluster nodes client ID to the external DNS secret. Stops external dns erroring if multiple service principals are found.
=> feat: add cluster node clientID to dns secret for Azure

src/Makefile.mk
Adding `--force-conflicts` flag to kubectl apply to fix conflicts, override value, and be sole manager ([docs](https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts))
=> chore: add --force-conflicts flag to kubectl apply

charts/grafana/loki/defaults.yaml, charts/grafana/loki/values.yaml
- JX-Observability charts are out of date and need updating to avoid drift
- Upgrade Loki from helm version 2.5.0 > 5.36.3
- Important to note that there are a few changes with how Loki is deployed and has been added to the PR
- With the upgrade, the current statefulset will be removed and re-added (pvc will be claimed by new statefulset)
- The upgrade comes with a few deployments that are defaulted to true, therefore changed to false as unnecessary. 
- offer single binary deployment - easy to customise with k8s config.
- Update Grafana/Promtail/Prometheus
=> feat: upgrade Loki charts

charts/grafana/promtail/defaults.yaml
- Promtail out of date
- Upgrade Promtail from 3.5.0 > 6.15.3
- No changes needed - upgrade regen and worked properly on a test cluster
=> feat: upgrade promtail helm v6.15.3

git/github.com/jenkins-x/jx3-pipeline-catalog.yml
=> fixe: remove non existing parameter --deadline from golangci-lint

.lighthouse/jenkins-x/release.yaml, .lighthouse/jenkins-x/release/promote-vs.sh
We have multiple "general purpose" jx images. I'm trying to reduce that since it easily causes version mismatch of installed tools. I currently noticed that ghcr.io/jenkins-x/jx and ghcr.io/jenkins-x/jx-boot have different version of kpt...
Since jx-boot is used a lot I don't see much point in using it more; nodes are likely to have downloaded it anyway.
=> fix: promote-vs.sh

.github/workflows/update-charts.yml, charts/jxgh/pusher-wave/defaults.yaml, charts/wave-k8s/wave/defaults.yaml
The action Update charts in the version stream [partially reverted](https://github.com/jenkins-x/jx3-versions/pull/3909) [my change](https://github.com/jenkins-x/jx3-versions/pull/3881). This PR fixes this, upgrades wave and hopefully prevents further unwanted changes by the action.
=> fix: restore switch from pusher-wave to wave

charts/autoscaler/cluster-autoscaler/defaults.yaml, charts/autoscaler/cluster-autoscaler/values.yaml.gotmpl, charts/repositories.yml
https://github.com/helm/charts/tree/master/stable/cluster-autoscaler is frozen since a long time. his PR adds the maintained helm chart for cluster autoscaler.
=> feat: add maintained cluster autoscaler helm chart

.lighthouse/jenkins-x/release.yaml, .lighthouse/jenkins-x/release/promote-vs.sh
also reduce risk of leaking secret in logs
stop trying to upgrade archived repository
=> fix: mark jx release as latest

src/get-selectors-by-release-and-clean.sh
Create `get-selectors-by-release-and-clean.sh`, which allows `HELMFILE_GLOBAL_FLAGS` to select by releases that have changed per-namespace. Useful for PRs where only a small number of releases are changed at-a-time.
In particular, the script compares changes to the local branch and main, making cautious decisions about what to select based on files that have changed. i.e.:
**Changes outside base `helmfiles/` directory:**
- Action: Perform a full cluster-wide with a "bare" `helmfile template` command
- Cleanup command(s): `rm -rf ${OUTPUT_DIR}/*/*/`
- helmfile selector: "" (empty string)
- Explanation: Any changes outside of `helmfiles/` are treated with caution by default - do a full regen
**Changes within `helmfiles/{$namespace}/helmfile.yaml` outside of specific helm release versions:** …
=> feat: script to filter helmfile selector by release name

charts/jetstack/cert-manager/defaults.yaml
Until support for not adding jx-values.yaml is added we need to stay on a version below 1.16
See https://kubernetes.slack.com/archives/C9MBGQJRH/p1728626859862409
I have started to work on a [proper solution](https://github.com/jenkins-x/jx-helpers/pull/419), but until then we need to downgrade.
=> fix: schema problem with cert-manager

charts/jxgh/lighthouse/values.yaml.gotmpl
it has apparently caused confusion
https://kubernetes.slack.com/archives/C9MBGQJRH/p1728470192325489
=> chore: remove unused value

charts/ingress-nginx/ingress-nginx/defaults.yaml, charts/repositories.yml
Currently chart upgrade for ingress-nginx does not work https://github.com/jenkins-x/jx3-versions/actions/runs/12681762739/job/35346055685#step:4:16:
```
repository prefix ingress-nginx has no URL in charts/repositories.yml
```
This should hopefully fix it.
=> chore: Add missing prefix for ingress-nginx and fix gitUrl

charts/jxgh/lighthouse/values.yaml.gotmpl
LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG is missing, which give warning logs 
To enable LIGHTHOUSE_TRIGGER_ON_MISSING the variable should not be set (no, not very logical). The value enable is interpreted as the name of a repository to disable trigger on missing for.
=> fix: correct env variables for keeper

.github/workflows/update-charts/updatebot.yaml
It's not really needed since updatebot is run in the lighthouse release pipeline as well.
Also removing repository prefixes that aren't used anymore
=> fix: exclude automatic lighthouse upgrade

charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
They don't play well with `helm template`.
If cert-manager is installed use that to setup secrets instead otherwise skip the admission webhook
=> fix: disable nginx jobs
