- jenkins-x-gke.yml
- jenkins-x-tls.yml
- jx/bdd/gke/ci.sh
- jx/bdd/tls/ci-old.sh
- jx/bdd/tls/ci.sh
also try migrate the TLS BDD test
> fix: support PRs on different forks

- apps/bitnami/external-dns/values.yaml.gotmpl
- apps/jenkins-x/bucketrepo/values.yaml.gotmpl
- apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- apps/jenkins-x/tekton/values.yaml.gotmpl
> fix: switch to terraform naming conventions

- apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- jx/bdd/ci.sh
so that we can reuse jxRequirements.yml in the jxboot-helmfile-resources
chart
> fix: fix helmfile template regression

- jx/bdd/ci.sh
now that we have: jx secret populate
so secrets are defaulted OOTB
> fix: simplify the BDD test

- charts/jenkins-x/jxboot-helmfile-resources.yml
> fix: upgrade jxboot-helmfile-resources

- charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
- charts/jenkins-x/tekton/defaults.yaml
- charts/jenkins-x/tekton/secret-schema.yaml
- jenkins-x-gke-ghe.yml
- jx/bdd/ci.sh
- jx/bdd/ghe/README.md
- jx/bdd/ghe/ci.sh
and default the docker config.json to be able to use docker.io
> fix: upgrade tekton

- charts/jenkins-x/tekton/defaults.yaml
- charts/jenkins-x/tekton/secret-schema.yaml
- charts/jenkins-x/tekton/values.yaml.gotmpl
- src/fake-secrets.yaml.gotmpl
and use docker config.json syntax for secrets
> fix: upgrade to latest tekton

- charts/cdf/tekton-pipeline/defaults.yaml
- charts/cdf/tekton-pipeline/secret-schema.yaml
- charts/cdf/tekton-pipeline/values.yaml.gotmpl
- charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
- charts/jenkinsci/jenkins/secret-schema.yaml
- charts/jenkinsci/jenkins/values.yaml.gotmpl
- charts/repositories.yml
- jx/bdd/ci.sh
- src/Makefile.mk
- tests/go.mod
- tests/go.sum
which is more optimised to be faster to deal with project imports etc
> fix: switch to the new jx gitops apply step

- charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- jx/bdd/terraform-ci.sh
so that the IAM bindings match up properly
> fix: use correct SA name for controller build

- charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
- charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
- charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
- schedulers/default.yaml
- schedulers/environment.yaml
- schedulers/in-repo.yaml
- schedulers/jx-meta-pipeline.yaml
so we can easily protect an ingress behind basic auth
> fix: add jx-basic-auth support

- charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
missed a cred-helper for Tekton
> feat: modified acr helper for tekton registry auth

- charts/jx3/jx-preview/defaults.yaml
until we fix the 1.16/1.17 CRD
> fix: lets pin the jx-preview version for now

- charts/cdf/tekton-pipeline/values.yaml.gotmpl
- charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- charts/jenkins-x/tekton/values.yaml.gotmpl
> fix: match role and service account names with terraform resources

- charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
- charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- charts/jx3/jx-build-controller/defaults.yaml
- charts/jx3/jx-build-controller/values.yaml.gotmpl
and remove the old jxboot-helmfile-resources nested chart
> fix: upgrade to jx-build-controller chart

- charts/jenkins-x/bucketrepo/defaults.yaml
- quickstarts.yaml
and add new file which jx-project will use soon
> fix: ugprade bucket repository chart

- charts/bitnami/external-dns/values.yaml.gotmpl
> fix(eks): fix wrong iam role for external-dns sa

- charts/jenkins-x/lighthouse/values.yaml.gotmpl
- src/Makefile.mk
to reduce the number of github API calls
> fix: upgrade lighthouse

- git-operator/job-gsm.yaml
- src/Makefile.mk
if using a sidecar for secrets (such as for GSM)
> fix: lets make sure we shut down the sidecar

- src/Makefile.mk
also lets always run secrets populate in case a PR merges which requires a
new secret
> fix: lets generate the jenkins jobs before we resolve helmfile

- charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
- charts/jenkinsci/jenkins/values.yaml.gotmpl
- jenkins/templates/job.gotmpl
so things work with multi branch projects and github OOTB and we can output
pipelines to PipelineActivity resources for visualisation on the CLI /
octant / dashboard
> fix: improve the jenkins integration

- charts/banzaicloud-stable/vault-operator/defaults.yaml
- charts/jx3/vault-instance/defaults.yaml
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
> fix: upgrade vault chart

- charts/bitnami/external-dns/defaults.yaml
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
Been running this one locally for awhile
> fix: upgrade external-dns chart

- .lighthouse/jenkins-x/bdd/bbs/README.md
- .lighthouse/jenkins-x/bdd/bbs/ci.sh
- .lighthouse/jenkins-x/bdd/bbs/setup.sh
- .lighthouse/jenkins-x/bdd/vault-kapp/README.md
- .lighthouse/jenkins-x/bdd/vault-kapp/ci.sh
- .lighthouse/jenkins-x/bdd/vault-kapp/job-overlay.yaml
- .lighthouse/jenkins-x/bdd/vault-kapp/overlay.sh
- .lighthouse/jenkins-x/pullrequest-bbs.yaml
- .lighthouse/jenkins-x/triggers.yaml
- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
also add vault-kapp and BBS test
> fix: upgrade catalog

- src/Makefile.mk
and also enable jx health OOTB
> fix: use a less noisy makefile

- charts/stable/cert-manager/defaults.yaml
> refactor: remove deprecated certmanager chart

- charts/osiris/osiris/defaults.yaml
- charts/osiris/osiris/values.yaml.gotmpl
- charts/repositories.yml
make it easy for people to install osiris, to automatically scale down unused pods in preview environments
see https://github.com/dailymotion-oss/osiris
I also wrote an admin guide in the docs to help people install it: https://github.com/jenkins-x/jx-docs/pull/3280
> feat: add default values for osiris

- .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
as sometimes TF is connected to the wrong cluster ;)
> fix: lets avoid terraform removing k8s resources

- charts/jx3/jxboot-helmfile-resources/secret-schema.yaml
- git/github.com/jenkins-x-terraform/terraform-jx-azure.yml
- git/github.com/jenkins-x/terraform-aws-eks-jx.yml
- git/github.com/jenkins-x/terraform-azurerm-jx.yml
for https://github.com/jenkins-x-plugins/jx-secret/issues/285
> fix: lets only recreate the htpasswd secret if empty

- charts/jenkinsci/jenkins/values.yaml.gotmpl
these values seem to work better on the latest jenkins chart
also lets add in the tekton plugin by default
> fix: add better defaults for jenkins

- src/Makefile.mk
so that report generation can generate CRDs too if required. e.g. generate Helm CRDs for better observability
> fix: move report generation into the main build

- charts/jx3/jxboot-helmfile-resources/secret-schema.yaml
- tests/jxboot_helmfile_resources_test.go
- tests/test_data/template/expected/tekton-container-registry-auth/.dockerconfigjson/eks-use-ecr-with-registry.json
use correct order on `contains` function!
> fix: fixes EKS + ECR

- src/Makefile.mk
so that we properly label (build) any report generated resources (e.g. chart metadata) to avoid wackiness during the preview/release of report generated k8s resources
> fix: better handling of report and status

- src/Makefile.mk
to ensure lighthouse stays in sync with the catalog git SHAs and avoids caching issues
> fix: trigger restart of lighthouse on boot job

- charts/jx3/lighthouse-telemetry-plugin/defaults.yaml
- charts/jx3/lighthouse-telemetry-plugin/values.yaml
see https://github.com/jenkins-x/lighthouse-telemetry-plugin
> chore: add lighthouse-telemetry-plugin

- src/Makefile.mk
to ensure commits show up nicely in github.com
> fix: lets ensure we setup the git user/email correctly

- mlprojectsets.yaml
- mlquickstarts.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
> feat: Add initial MLOps assets to versionStream

- src/Makefile.mk
to reduce git conflicts
fixes https://github.com/jenkins-x/issues/issues/42
> fix: avoid modifying git with the git sha

- mlprojectsets.yaml
- mlquickstarts.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
> feat: Migrate mlquickstarts

- mlprojectsets.yaml
- mlquickstarts.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
> fix: MNIST dataset location has changed

- charts/jx3/lighthouse/values.yaml.gotmpl
its easy to disable this locally if you need to
> fix: retrigger PR pipelines on merge by default

- charts/jx3/lighthouse-webui-plugin/defaults.yaml
- charts/jx3/lighthouse-webui-plugin/values.yaml
https://github.com/jenkins-x-plugins/lighthouse-webui-plugin
> chore: add lighthouse-webui-plugin

- charts/osiris/osiris/defaults.yaml
improve performances (use less memory) since previous version
> chore: upgrade osiris to 0.0.55

- src/Makefile.mk
so we can rebase better on production PRs
> fix: force push PRs on environments

- src/Makefile.mk
as we may not have cloud IAM roles to read current secrets so we may try populate default values
> fix: disable secret populate on PRs

- charts/grafana/tempo/values.yaml
to help troubleshoot tempo issues
> fix: allow prometheus to scrape tempo metrics

- charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
If secret with key and certificate exists then use it instead of LetsEncrypt
> feat: Added secret with predefined customer's certificates and private key

- charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
> feat: set url from requirements file for external vault

- charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
> fix: run vault login in external secrets init container

- charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
> fix: set only vault_addr for external vault

- src/Makefile.mk
> feat: add external vault env variable to makefile

- git-operator/job-azurekeyvault.yaml
- git-operator/job-gsm.yaml
- git-operator/job-vault.yaml
- git-operator/job.yaml
> refactor: downgrade jx boot to 3.2.213

- .lighthouse/jenkins-x/release/promote-vs.sh
- .lighthouse/jenkins-x/release/recreate-vs.sh
> chore: auto-promote version stream changes to k3s gitops repo

- git/github.com/jenkins-x/terraform-aws-eks-jx.yml
from: https://github.com/jenkins-x/terraform-aws-eks-jx
> chore(deps): upgrade jenkins-x/jx3-versions to version 1.18.4

- git/github.com/jenkins-x/terraform-aws-eks-jx.yml
from: https://github.com/jenkins-x/terraform-aws-eks-jx
> chore(deps): upgrade jenkins-x/jx3-versions to version 1.18.5

- charts/jxgh/jx-build-controller/defaults.yaml
- charts/jxgh/jx-preview/defaults.yaml
- charts/jxgh/jx-slack/defaults.yaml
- charts/jxgh/jxboot-helmfile-resources/defaults.yaml
> chore: bump all charts except tekton

- .github/workflows/bdd-kind.yml
- .github/workflows/update-charts.yml
- .github/workflows/update-go.yml
- .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-kubevault.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
- .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
- .lighthouse/jenkins-x/pullrequest-bbc.yaml
- .lighthouse/jenkins-x/pullrequest-bbs.yaml
- .lighthouse/jenkins-x/pullrequest-eks.yaml
- .lighthouse/jenkins-x/pullrequest-ghe.yaml
- .lighthouse/jenkins-x/pullrequest-gitea.yaml
- .lighthouse/jenkins-x/pullrequest-gitlab.yaml
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
- charts/jxgh/jxboot-helmfile-resources/defaults.yaml
- git-operator/job-azurekeyvault.yaml
- git-operator/job-gsm.yaml
- git-operator/job-vault.yaml
- git-operator/job.yaml
- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
- packages/jx.yml
> chore: update jxboot helmfile chart

- charts/jetstack/cert-manager/defaults.yaml
- charts/jxgh/jx-preview/defaults.yaml
- charts/jxgh/jxboot-helmfile-resources/defaults.yaml
> chore: update certmanager to 1.4.4

- charts/ingress-nginx/ingress-nginx/defaults.yaml
> chore: upgrade nginx chart to 4.1.0

- .github/workflows/update-charts/updatebot.yaml
> fix: auto update nginx helm chart

- git/github.com/jenkins-x-terraform/terraform-jx-azure.yml
Server side apply should now be working as expected
> chore: upgrade terraform versionstream

- .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
> fix: use spot instances instead of pre-emptible

- charts/bitnami/external-dns/defaults.yaml
> fix: downgrade ex-dns to 6.4.5

- .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
- .lighthouse/jenkins-x/pullrequest.yaml
> fix: modify tf yaml after tf operator upgrade

- .lighthouse/jenkins-x/bdd/terraform-ci.sh
Improved logging
Fix inspection warnings
> fix: Verify pod result

- .lighthouse/jenkins-x/bdd/terraform-ci.sh
- charts/jxgh/lighthouse/defaults.yaml
from: https://github.com/jenkins-x/lighthouse.git
> chore(deps): upgrade jenkins-x/lighthouse to version 1.9.0

- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Signed-off-by: osamamagdy <osamamagdy174@gmail.com>
> feat: update version for catalog

- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Signed-off-by: osamamagdy <osamamagdy174@gmail.com>
> fix: edit catalog reference

- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
> fix: update catalog to fix syft binary missing from PATH

- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
> fix: upgrade catalog to fix incorrect bash shell in oras

- charts/cdf/tekton-pipeline/defaults.yaml
This upgrades tekton to 0.32.4
> chore: upgrade tekton chart to 0.1.0

- .lighthouse/jenkins-x/release/promote-vs.sh
jx3-kubernetes-production is intended for remote clusters and should thus have the environment-remote pipelines
>  fix: Switch to remote environment pipelines

- charts/jxgh/jx-ui/defaults.yaml
- charts/jxgh/jx-ui/values.yaml.gotmpl
> feat: add jx ui chart to version stream

- src/Makefile.mk
Only check repos where hook has not been added before
> feat: Make update of webhooks fast

- schedulers/default.yaml
- schedulers/environment-review-required.yaml
- schedulers/environment.yaml
- schedulers/in-repo.yaml
- schedulers/jx-meta-pipeline.yaml
Relates to jenkins-x/lighthouse#1491
> fix: Remove references to non-existing plugins

- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
> fix: manually bump catalog version to upgrade to updatebot 0.3.6

- charts/cdf/tekton-pipeline/defaults.yaml
- src/Makefile.mk
- src/kpt-live-apply-wrapper.sh
Also cleaning up a bit
Using this feature would fix jenkins-x/jx#8024
Note: Since kpt is very strict about the yaml syntax there is still one more fix needed for kpt to work:
cdfoundation/tekton-helm-chart#28
Depends on jenkins-x-plugins/jx-gitops#891
> feat: Add support for kpt live apply

- src/Makefile.mk
- src/get-selectors-and-clean.sh
Add Makefile options to regenerete only namespaced with changes using helmfile selectors.
> feat: add selector option to Makefile. Regenerate only namespace with changes

- charts/cdf/tekton-pipeline/defaults.yaml
> chore: upgrade tekton to 0.33.4

- git/github.com/jenkins-x/jx3-pipeline-catalog.yml
> chore: upgrade version stream to point to go 1.19.3

- .github/workflows/update-go.yml
The current version of the jx-updatebot image lacks go
> chore: upgrade jx updatebot

- src/Makefile.mk
need to commit earlier so the report is committed before jx changelog is run
> fix: faulty dependency updates in changelog

- charts/jxgh/pusher-wave/defaults.yaml
- charts/repositories.yml
- charts/wave-k8s/wave/defaults.yaml
- src/Makefile.mk
Requires jenkins-x-plugins/jx-gitops#959
> fix: replace own wave chart with upstream one

- charts/jetstack/cert-manager/defaults.yaml
Reverts jenkins-x/jx3-versions#3960
> Revert "chore: upgrade charts"

- .lighthouse/jenkins-x/release/promote-vs.sh
also removing archived repository jx3-gke-gcloud-vault
> fix: make jx gitops kpt update not add update too much

- charts/bank-vaults/vault-operator/defaults.yaml
- charts/banzaicloud-stable/vault-operator/defaults.yaml
- charts/repositories.yml
part of fix for jenkins-x/jx#8688
requires jenkins-x-plugins/jx-gitops#972
> fix: replace broken helm repository and upgrade bank-vault

- charts/bitnami-oci/external-dns/values.yaml.gotmpl
related to jenkins-x/jx3-versions#4224
> chore: use image from bitnamilegacy

- charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
> fix: imagepull error
